# Full configuration reference: https://github.com/csarrazi/CsaGuzzleBundle/blob/2.x/src/Resources/doc/configuration_reference.md#configuration-reference
# Available client config options: http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client
# and http://docs.guzzlephp.org/en/latest/request-options.html
csa_guzzle:
    profiler: '%kernel.debug%'
    logger: true
    clients:
        oauth:
            config:
                base_url: https://github.com
        api:
            config:
                base_url: https://api.github.com
        my_api:
            config:
                base_url: '%my_api_url%'
