# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
    param_fetcher_listener:  true
    format_listener:
      rules:
        - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
        - { path: '^/', stop: true }
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=2.0']
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true
    exception:
        enabled: true
        codes:
            { App\Exception\ResourceValidationException: 400 }
        messages:
            { App\Exception\ResourceValidationException: true }
        exception_controller: 'fos_rest.exception.controller:showAction'
    versioning:
        enabled: true
        resolvers:
            media_type: # Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
