# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    oAuth_client_id: 28330298461-ehsvkkcl9iqc7a428u7h02tv0215sk8m.apps.googleusercontent.com
    oAuth_client_secret: StX1G47ze96Vi3b5uJP47xvn
    oAuth_url: https://www.googleapis.com/oauth2/v4/token
    oAuth_login_url: https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token=

    my_api_url: http://bilemo.com

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    oauth_authenticator:
        class: App\Security\OauthAuthenticator
        arguments: ["@csa_guzzle.client.oauth", "%oAuth_client_id%", "%oAuth_client_secret%", "@router"]

    oauth_user_provider:
        class: App\Security\OauthUserProvider
        arguments: ["@csa_guzzle.client.api", "@jms_serializer"]

    api_authenticator:
        class: App\Security\ApiAuthenticator

    api_user_provider:
        class: App\Security\ApiUserProvider
        arguments: ["@csa_guzzle.client.api", "@jms_serializer"]
