# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    github_client_id: febe88cb8aeec367b543
    github_client_secret: 9d8162ce74051a5f542ef23b705d9f726047c4de
    my_api_url: http://127.0.0.1:8000/

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    github_authenticator:
        class: App\Security\GithubAuthenticator
        arguments: ["@csa_guzzle.client.github_oauth", "%github_client_id%", "%github_client_secret%", "@router"]

    github_user_provider:
        class: App\Security\GithubUserProvider
        arguments: ["@csa_guzzle.client.github_api", "@jms_serializer"]
